### ISSUE TITLE
error: salt must be bytes

### ISSUE THREAD

**Issue by micklexqg** [github-pengge/PyTorch-progressive_growing_of_gans#24]
hi ,thanks for your work.
I came into the error: salt must be bytes.
what is the reason, have you counter it？

**Comment by jtx1999** [comment]
Hi, I'm facing the same error while running h5tool.py.
Did you resolve it? Thanks!

**Comment by AwesomeLemon** [comment]
For me calling ```str.encode``` on the string causing the problem solved it
